volumes:
  alephium-wallets: {}
  alephium-data: {}

services:
  alephium:
    image: alephium/alephium:latest
    restart: unless-stopped
    ports:
      - 9973:9973/tcp
      - 9973:9973/udp
      - 10973:10973/tcp
      - 12973:12973/tcp
    security_opt:
      - no-new-privileges:true
    volumes:
      - alephium-data:/alephium-home/.alephium
      - alephium-wallets:/alephium-home/.alephium-wallets
      - ./user.conf:/alephium-home/.alephium/user.conf
    healthcheck:
      test: ['CMD', 'curl', 'http://127.0.0.1:12973/infos/self-clique']
      timeout: 45s

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80  # Expose HTTP
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # NGINX configuration
    depends_on:
      - alephium
